# Generated by Django 3.0.5 on 2020-04-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_id', to='trivia_party.Player'),
        ),
    ]
