# Generated by Django 3.0.5 on 2020-05-16 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_party', '0004_auto_20200516_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=1048)),
                ('question_answers', models.CharField(blank=True, max_length=1048)),
                ('correct_answer', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('question_type', models.CharField(blank=True, max_length=255)),
                ('difficulty', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='num_rounds',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TriviaSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.CharField(blank=True, max_length=255)),
                ('score', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='trivia_party.Player')),
                ('trivia_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='trivia_party.Round')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='trivia_party.Party'),
        ),
    ]
