# Generated by Django 3.0.5 on 2020-05-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_party', '0006_auto_20200516_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviasubmission',
            name='trivia_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='trivia_party.TriviaQuestion'),
            preserve_default=False,
        ),
    ]
