# Generated by Django 3.0.6 on 2020-05-21 18:52

from django.db import migrations, models
from django.utils import timezone
from datetime import datetime
import pytz

now = timezone.now()


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_party', '0008_auto_20200520_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='round',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='triviaquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triviaquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='triviasubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triviasubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
