# Generated by Django 3.0.5 on 2020-05-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_auto_20200516_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='party_type',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sub_type',
        ),
        migrations.AddField(
            model_name='party',
            name='party_subtype',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='party_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
