# Generated by Django 3.0.5 on 2020-05-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_auto_20200516_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='trivia_round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='party.Round'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triviasubmission',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='party.Player'),
        ),
        migrations.AlterField(
            model_name='triviasubmission',
            name='trivia_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='party.Round'),
        ),
    ]
