# Generated by Django 3.0.6 on 2020-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0009_auto_20200521_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
