# Generated by Django 3.0.6 on 2020-05-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0010_party_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
