# Generated by Django 3.0.6 on 2020-05-24 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trivia_party', '0011_auto_20200521_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackCahCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_type', models.CharField(max_length=255, unique=True)),
                ('card_text', models.CharField(max_length=255, unique=True)),
                ('pick', models.IntegerField()),
                ('draw', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CahDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cah_deck', to='trivia_party.Party')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteCahCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_type', models.CharField(max_length=255, unique=True)),
                ('card_text', models.CharField(max_length=255, unique=True)),
                ('in_hand', models.BooleanField(default=False)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_cards', to='cah.CahDeck')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_cards', to='trivia_party.Player')),
            ],
        ),
        migrations.CreateModel(
            name='CahSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('black_cah_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cah_submissions', to='cah.BlackCahCard')),
                ('cah_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cah_submissions', to='trivia_party.Round')),
                ('picked_cards', models.ManyToManyField(blank=True, to='cah.WhiteCahCard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cah_submissions', to='trivia_party.Player')),
            ],
        ),
        migrations.AddField(
            model_name='blackcahcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_cards', to='cah.CahDeck'),
        ),
        migrations.AddField(
            model_name='blackcahcard',
            name='party_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_card', to='trivia_party.Round'),
        ),
        migrations.AddField(
            model_name='blackcahcard',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_cards', to='trivia_party.Player'),
        ),
    ]
