# Generated by Django 3.0.6 on 2020-05-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0003_auto_20200525_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitecahcard',
            name='dealt',
            field=models.BooleanField(default=False),
        ),
    ]
