# Generated by Django 3.0.6 on 2020-05-25 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_party', '0011_auto_20200521_2349'),
        ('cah', '0004_whitecahcard_dealt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackcahcard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_black_cards', to='trivia_party.Player'),
        ),
        migrations.AlterField(
            model_name='blackcahcard',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_black_cards', to='trivia_party.Player'),
        ),
    ]
