# Generated by Django 3.0.6 on 2020-06-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0005_auto_20200525_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitecahcard',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
    ]
