# Generated by Django 3.0.6 on 2020-06-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cah', '0006_whitecahcard_revealed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahsubmission',
            name='revealed',
            field=models.BooleanField(default=False),
        ),
    ]
